---
- name: Install Nginx
  dnf:
    name: nginx
    state: present

- name: Deploy Nginx Load Balancer Config
  template:
    src: nginx_frontend.conf.j2
    dest: /etc/nginx/nginx.conf
  notify: restart nginx

- name: Start Nginx
  service:
    name: nginx
    state: started
    enabled: true